
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "serviceEtudiant", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8081/?wsdl")
public class ServiceEtudiant
    extends Service
{

    private static final URL SERVICEETUDIANT_WSDL_LOCATION;
    private static final WebServiceException SERVICEETUDIANT_EXCEPTION;
    private static final QName SERVICEETUDIANT_QNAME = new QName("http://service/", "serviceEtudiant");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEETUDIANT_WSDL_LOCATION = url;
        SERVICEETUDIANT_EXCEPTION = e;
    }

    public ServiceEtudiant() {
        super(__getWsdlLocation(), SERVICEETUDIANT_QNAME);
    }

    public ServiceEtudiant(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEETUDIANT_QNAME, features);
    }

    public ServiceEtudiant(URL wsdlLocation) {
        super(wsdlLocation, SERVICEETUDIANT_QNAME);
    }

    public ServiceEtudiant(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEETUDIANT_QNAME, features);
    }

    public ServiceEtudiant(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceEtudiant(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceStudent
     */
    @WebEndpoint(name = "ServiceStudentPort")
    public ServiceStudent getServiceStudentPort() {
        return super.getPort(new QName("http://service/", "ServiceStudentPort"), ServiceStudent.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceStudent
     */
    @WebEndpoint(name = "ServiceStudentPort")
    public ServiceStudent getServiceStudentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "ServiceStudentPort"), ServiceStudent.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEETUDIANT_EXCEPTION!= null) {
            throw SERVICEETUDIANT_EXCEPTION;
        }
        return SERVICEETUDIANT_WSDL_LOCATION;
    }

}
