
package stub;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServiceStudent", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceStudent {


    /**
     * 
     * @return
     *     returns java.util.List<stub.Student>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listEtudiants", targetNamespace = "http://service/", className = "stub.ListEtudiants")
    @ResponseWrapper(localName = "listEtudiantsResponse", targetNamespace = "http://service/", className = "stub.ListEtudiantsResponse")
    @Action(input = "http://service/ServiceStudent/listEtudiantsRequest", output = "http://service/ServiceStudent/listEtudiantsResponse")
    public List<Student> listEtudiants();

}
